### ISSUE TITLE
[meta] requirements for wgpu-rs examples validation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#155]
This is what we are missing to load SPIR-Vs of wgpu-rs examples for introspection

- [x] (boids)
  - [x] `WorkgroupSize` builtin
  - [x] `UnsupportedInstruction(Function, Bitcast)`
  - [x] `UnsupportedExtInst(25)`
- [x] (mipmap, skybox) `InvalidWordCount` after `Switch` instruction
- [x] (shadow):
  - [x] `UnsupportedInstruction(Function, MatrixTimesMatrix)`
  - [x] `UnsupportedInstruction(Function, ConvertSToF)`
  - [x] `MissingDecoration(Offset)`
  - [x] `UnsupportedInstruction(Function, Bitcast)`
- [ ] (texture-array)
  - [ ] `InvalidImageExpression(Handle(10))`
- [x] (water)
  - [x] `UnsupportedExtInst(69)`
  - [x] `UnsupportedExtInst(49)`
  - [x] `UnsupportedInstruction(Function, Kill)`
  - [x] `UnsupportedInstruction(Function, ConvertSToF)`

**Comment by kvark** [comment]
Filed https://github.com/gfx-rs/naga/issues/161 for the bitcast operator

**Comment by kvark** [comment]
I believe all the examples (except for `texture-array`) are now validated for their interface. Issue can be closed 🎉
