### ISSUE TITLE
[meta] shader transformations

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#53]
This is a list of generic shader transformations that we need to do for WebGPU:
- [x] out-of-bound handling of accessing arrays in uniform and storage buffers. The index must be either clamped, or zeroes returned.
- [x] out-of-bound handling of accessing storage textures.
- [ ] zero-initialization of threadgroup memory in compute shaders

**Comment by jimblandy** [comment]
Out-of-bounds handling is implemented for both buffers and textures on HLSL, Vulkan, and MSL, and on WGSL by pass-through. GLSL is still needed, but OpenGL can't fully support `wgpu`, so I have checked those two boxes above.

**Comment by teoxoy** [comment]
Related to zero init of workgroup memory https://github.com/gfx-rs/wgpu/issues/2430
